plugins {
    id 'org.moddingx.modgradle.meta' version '5.0.3'
}

repositories {
    maven {
        name = 'ModMaven'
        url = 'https://modmaven.dev/'
    }
}

var dev = System.getenv('IS_DEV')?.toBoolean() ?: false
var baseVersion = '21.6'
var jeiVersion = '21.3.2.22'

mod.configure {
    modid 'ultimatools'
    group 'de.melanx'
    versioning {
        if (dev) {
            def gitCommitHash = ['git', 'rev-parse', 'HEAD'].execute().text.trim()
            constant baseVersion + (gitCommitHash ? "-${gitCommitHash}" : '')
        } else {
            base baseVersion
            maven 'https://maven.melanx.de/release'
        }
    }

    neoforge project.hasProperty('neo_version') ? project.neo_version : "${baseVersion}.8-beta"

    license 'MIT License'
    github 'ChaoticTrials/UltimaTools'

    changelog {
        def lines = defaultChangelog.toString().split('\n')
        def filteredChangelog = lines.findAll { !it.startsWith('- [[meta]') }.join('\n')

        return filteredChangelog
    }

    publishing {
        maven {
            name 'melanx'
            url 'https://maven.melanx.de/release'
            credentials(PasswordCredentials)
        }
    }

    upload {
        all {
            type 'release'
        }
        curseforge {
            projectId 315068
        }
        modrinth {
            projectId 'fM4ceeVu'
        }
    }
}

dependencies {
    compileOnly "mezz.jei:jei-1.21.5-neoforge:${jeiVersion}"
}
