modLoader="javafml"
loaderVersion="[${fml},)"
issueTrackerURL="https://github.com/MelanX/ultimatools/issues/"
license="MIT License"

[[mods]]
modId="ultimatools"
version="${version}"
displayName="Skyblock Ultima Tools"
updateJSONURL="https://assets.melanx.de/updates/skyblock-ultima-tools.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/skyblock-ultima-tools"
authors="MelanX"

[[dependencies.ultimatools]]
    modId="forge"
    mandatory=true
    versionRange="[${forge},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ultimatools]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft},)"
    ordering="NONE"
    side="BOTH"
