modLoader="javafml"
loaderVersion="[38,)"
issueTrackerURL="https://github.com/MelanX/ultimatools/issues/"
license="MIT License"

[[mods]]
modId="ultimatools"
version="${file.jarVersion}"
displayName="Skyblock Ultima Tools"
updateJSONURL="https://assets.melanx.de/updates/skyblock-ultima-tools.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/skyblock-ultima-tools"
authors="MelanX"

[[dependencies.ultimatools]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ultimatools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18, 1.19)"
    ordering="NONE"
    side="BOTH"