modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${license}"
issueTrackerURL="https://github.com/ChaoticTrials/UltimaTools/issues"

[[mods]]
modId="ultimatools"
version="${mod_version}"
displayName="Skyblock Ultima Tools"
updateJSONURL="https://assets.melanx.de/updates/skyblock-ultima-tools.json"
displayURL="https://modrinth.com/user/MelanX"
authors="MelanX"
description="""
Useful tools for Skyblock modpacks
"""

[[dependencies.${modid}]]
   modId = "neoforge"
   type = "required"
   versionRange = "[${neo_version},)"
   ordering="NONE"
   side="BOTH"

[[dependencies.${modid}]]
   modId="minecraft"
   type="required"
   versionRange="[${minecraft_version},)"
   ordering="NONE"
   side="BOTH"
